// <auto-generated />
using System;
using Galaxi.Movie.Persistence.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Galaxi.Movie.Persistence.Migrations
{
    [DbContext(typeof(MovieContextDb))]
    [Migration("20240926193431_addtrailerattributte3")]
    partial class addtrailerattributte3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Galaxi.Movie.Data.Models.Film", b =>
                {
                    b.Property<Guid>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cast")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Director")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origincountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PosterImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Trailer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("duration")
                        .HasColumnType("int");

                    b.HasKey("FilmId");

                    b.ToTable("Films", (string)null);

                    b.HasData(
                        new
                        {
                            FilmId = new Guid("b10b662a-2ae0-42d5-aae7-5209b6e76e7c"),
                            Cast = "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology.",
                            Director = "Christopher Nolan",
                            Genre = "Science Fiction",
                            Language = "English",
                            Origincountry = "USA",
                            PosterImage = "https://i.pinimg.com/564x/43/9a/1c/439a1c4583a953c26b63d08a1d832f53.jpg",
                            Title = "Inception",
                            Trailer = "https://www.youtube.com/embed/YoHD9XEInc0?si=FOzAaTEzqc0YA6sK",
                            classification = "B",
                            duration = 148
                        },
                        new
                        {
                            FilmId = new Guid("689e687e-d7e2-4b85-82c7-5a0f67f2803d"),
                            Cast = "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong",
                            Description = "A poor family schemes to become employed by a wealthy family.",
                            Director = "Bong Joon-ho",
                            Genre = "Thriller",
                            Language = "English",
                            Origincountry = "South Korea",
                            PosterImage = "https://i.pinimg.com/564x/a9/7d/26/a97d26449214bb756c75b4ed88d7b06e.jpg",
                            Title = "Parasite",
                            Trailer = "https://www.youtube.com/embed/5xH0HfJHsaY?si=uqPRQpiUUcnkOmgw",
                            classification = "B15",
                            duration = 132
                        },
                        new
                        {
                            FilmId = new Guid("b5d198e3-be36-4ec9-b3f6-73efd7f3d921"),
                            Cast = "Marlon Brando, Al Pacino, James Caan",
                            Description = "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
                            Director = "Francis Ford Coppola",
                            Genre = "Crime",
                            Language = "English",
                            Origincountry = "USA",
                            PosterImage = "https://i.pinimg.com/564x/1d/fa/6c/1dfa6ce2aca118aeddd66249d425c575.jpg",
                            Title = "The Godfather",
                            Trailer = "https://www.youtube.com/embed/UaVTIH8mujA?si=YCmw9CNpLsz-8jqw",
                            classification = "B15",
                            duration = 175
                        },
                        new
                        {
                            FilmId = new Guid("89ba1499-f8bb-4e60-91de-cd8a66bed0d8"),
                            Cast = "Audrey Tautou, Mathieu Kassovitz, Rufus",
                            Description = "Amélie is an innocent and naive girl in Paris with her own sense of justice.",
                            Director = "Jean-Pierre Jeunet",
                            Genre = "Romantic Comedy",
                            Language = "French",
                            Origincountry = "France",
                            PosterImage = "https://i.pinimg.com/564x/d8/9e/ac/d89eac7350c0c7d61b8ca8b22863c398.jpg",
                            Title = "Amélie",
                            Trailer = "https://www.youtube.com/embed/Py7cDXQae2U?si=1EKFakxcxr0AyumX",
                            classification = "AA",
                            duration = 122
                        },
                        new
                        {
                            FilmId = new Guid("444770a0-0bf1-4397-8ef8-436e5fd479ee"),
                            Cast = "John Travolta, Uma Thurman, Samuel L. Jackson",
                            Description = "The lives of two mob hitmen, a boxer, and a pair of bandits intertwine in four tales of violence.",
                            Director = "Quentin Tarantino",
                            Genre = "Crime",
                            Language = "English",
                            Origincountry = "USA",
                            PosterImage = "https://i.pinimg.com/564x/e4/05/0b/e4050b92335cde4a3b5ae340fc8c5ee3.jpg",
                            Title = "Pulp Fiction",
                            Trailer = "https://www.youtube.com/embed/tGpTpVyI_OQ?si=cyNza1EHuoMQq8DM",
                            classification = "C",
                            duration = 154
                        },
                        new
                        {
                            FilmId = new Guid("3322382a-b848-4d38-bd1f-7703f30d2f2b"),
                            Cast = "Anthony Gonzalez, Gael García Bernal, Benjamin Bratt",
                            Description = "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead.",
                            Director = "Lee Unkrich",
                            Genre = "Animation",
                            Language = "English",
                            Origincountry = "USA",
                            PosterImage = "https://i.pinimg.com/564x/7a/6d/c4/7a6dc4222a7bd3037d9f7146314e3bc7.jpg",
                            Title = "Coco",
                            Trailer = "https://www.youtube.com/embed/awzWdtCezDo?si=UnEw3ZYXDm6Nl2ER",
                            classification = "AA",
                            duration = 105
                        },
                        new
                        {
                            FilmId = new Guid("cb57f558-fccc-4419-9b30-125903a5a8cd"),
                            Cast = "Christian Bale, Heath Ledger, Aaron Eckhart",
                            Description = "Batman begins his fight against crime in Gotham.",
                            Director = "Christopher Nolan",
                            Genre = "Action",
                            Language = "English",
                            Origincountry = "USA",
                            PosterImage = "https://i.pinimg.com/564x/ea/a2/6e/eaa26e2c3bfa234c3cdd3c4d9fabad35.jpg",
                            Title = "The Dark Knight",
                            Trailer = "https://www.youtube.com/embed/EXeTwQWrcwY?si=H-7BhelqVXKIAmTb",
                            classification = "B",
                            duration = 152
                        },
                        new
                        {
                            FilmId = new Guid("0b5148f0-07d4-4f4b-97b2-a0ea46a40781"),
                            Cast = "Rumi Hiiragi, Miyu Irino, Mari Natsuki",
                            Description = "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.",
                            Director = "Hayao Miyazaki",
                            Genre = "Animation",
                            Language = "English",
                            Origincountry = "Japan",
                            PosterImage = "https://i.pinimg.com/736x/93/6b/c2/936bc2c8a46385dddd69ecaa1fe1d2d5.jpg",
                            Title = "Spirited Away",
                            Trailer = "https://www.youtube.com/embed/ByXuk9QqQkk?si=Q1sCfN5g2wRvZPU4",
                            classification = "A",
                            duration = 125
                        },
                        new
                        {
                            FilmId = new Guid("02b826f2-8dfb-4c15-ae59-b9176f00e5ad"),
                            Cast = "Ivana Baquero, Ariadna Gil, Sergi López",
                            Description = "In the falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.",
                            Director = "Guillermo del Toro",
                            Genre = "Fantasy",
                            Language = "Spanish",
                            Origincountry = "Spain",
                            PosterImage = "https://i.pinimg.com/564x/0d/e1/d9/0de1d966d8bc5bd1867a7572fa87651f.jpg",
                            Title = "Pan's Labyrinth",
                            Trailer = "https://www.youtube.com/embed/jVZRnnVSQ8k?si=dCJTObQtyk62LIwd",
                            classification = "B15",
                            duration = 118
                        },
                        new
                        {
                            FilmId = new Guid("158671d2-8375-4c41-ab05-2279a91832b6"),
                            Cast = "Liam Neeson, Ralph Fiennes, Ben Kingsley",
                            Description = "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.",
                            Director = "Steven Spielberg",
                            Genre = "Biography",
                            Language = "English",
                            Origincountry = "USA",
                            PosterImage = "https://i.pinimg.com/564x/58/7a/2a/587a2a1dbb33437d4c48811e020c4ec8.jpg",
                            Title = "Schindler's List",
                            Trailer = "https://www.youtube.com/embed/mxphAlJID9U?si=14XT-lhGvOhmsl06",
                            classification = "C",
                            duration = 195
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
