// <auto-generated />
using System;
using Galaxi.Movie.Persistence.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Galaxi.Movie.Persistence.Migrations
{
    [DbContext(typeof(MovieContextDb))]
    [Migration("20240804214739_updateEnums")]
    partial class updateEnums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Galaxi.Movie.Data.Models.Film", b =>
                {
                    b.Property<Guid>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cast")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Director")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origincountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PosterImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("duration")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("FilmId");

                    b.ToTable("Films", (string)null);

                    b.HasData(
                        new
                        {
                            FilmId = new Guid("335fe6f1-fd20-4bf6-97ce-47c7ba51d46f"),
                            Cast = "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology.",
                            Director = "Christopher Nolan",
                            Genre = "Science Fiction",
                            Language = "English",
                            Origincountry = "USA",
                            PosterImage = "inception.jpg",
                            Title = "Inception",
                            classification = "B",
                            duration = 148
                        },
                        new
                        {
                            FilmId = new Guid("f2b5f6f1-1562-4d32-90c7-a1551bd64265"),
                            Cast = "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong",
                            Description = "A poor family schemes to become employed by a wealthy family.",
                            Director = "Bong Joon-ho",
                            Genre = "Thriller",
                            Language = "English",
                            Origincountry = "South Korea",
                            PosterImage = "parasite.jpg",
                            Title = "Parasite",
                            classification = "B15",
                            duration = 132
                        },
                        new
                        {
                            FilmId = new Guid("d7d0587c-2125-408c-8c17-9a04b28c15c9"),
                            Cast = "Marlon Brando, Al Pacino, James Caan",
                            Description = "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
                            Director = "Francis Ford Coppola",
                            Genre = "Crime",
                            Language = "English",
                            Origincountry = "USA",
                            PosterImage = "godfather.jpg",
                            Title = "The Godfather",
                            classification = "B15",
                            duration = 175
                        },
                        new
                        {
                            FilmId = new Guid("e033037f-f006-4423-ad19-f338fd60adcd"),
                            Cast = "Audrey Tautou, Mathieu Kassovitz, Rufus",
                            Description = "Amélie is an innocent and naive girl in Paris with her own sense of justice.",
                            Director = "Jean-Pierre Jeunet",
                            Genre = "Romantic Comedy",
                            Language = "French",
                            Origincountry = "France",
                            PosterImage = "amelie.jpg",
                            Title = "Amélie",
                            classification = "AA",
                            duration = 122
                        },
                        new
                        {
                            FilmId = new Guid("c8bd6cc4-0be1-4921-b2fa-831e0197ec29"),
                            Cast = "John Travolta, Uma Thurman, Samuel L. Jackson",
                            Description = "The lives of two mob hitmen, a boxer, and a pair of bandits intertwine in four tales of violence.",
                            Director = "Quentin Tarantino",
                            Genre = "Crime",
                            Language = "English",
                            Origincountry = "USA",
                            PosterImage = "pulpfiction.jpg",
                            Title = "Pulp Fiction",
                            classification = "C",
                            duration = 154
                        },
                        new
                        {
                            FilmId = new Guid("005c30a9-e3ea-49af-8f72-a335c11488d1"),
                            Cast = "Anthony Gonzalez, Gael García Bernal, Benjamin Bratt",
                            Description = "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead.",
                            Director = "Lee Unkrich",
                            Genre = "Animation",
                            Language = "English",
                            Origincountry = "USA",
                            PosterImage = "coco.jpg",
                            Title = "Coco",
                            classification = "AA",
                            duration = 105
                        },
                        new
                        {
                            FilmId = new Guid("f486d6ed-b405-426f-8ab3-25f424ac9f58"),
                            Cast = "Christian Bale, Heath Ledger, Aaron Eckhart",
                            Description = "Batman begins his fight against crime in Gotham.",
                            Director = "Christopher Nolan",
                            Genre = "Action",
                            Language = "English",
                            Origincountry = "USA",
                            PosterImage = "darkknight.jpg",
                            Title = "The Dark Knight",
                            classification = "B",
                            duration = 152
                        },
                        new
                        {
                            FilmId = new Guid("4b4a0167-9ad1-438b-9982-59415943cc50"),
                            Cast = "Rumi Hiiragi, Miyu Irino, Mari Natsuki",
                            Description = "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.",
                            Director = "Hayao Miyazaki",
                            Genre = "Animation",
                            Language = "English",
                            Origincountry = "Japan",
                            PosterImage = "spiritedaway.jpg",
                            Title = "Spirited Away",
                            classification = "A",
                            duration = 125
                        },
                        new
                        {
                            FilmId = new Guid("d93a8915-155a-4eb9-88c3-6573567a6a9c"),
                            Cast = "Ivana Baquero, Ariadna Gil, Sergi López",
                            Description = "In the falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.",
                            Director = "Guillermo del Toro",
                            Genre = "Fantasy",
                            Language = "Spanish",
                            Origincountry = "Spain",
                            PosterImage = "panslabyrinth.jpg",
                            Title = "Pan's Labyrinth",
                            classification = "B15",
                            duration = 118
                        },
                        new
                        {
                            FilmId = new Guid("1e963cde-fe0c-4448-b541-b81ec5fe04ec"),
                            Cast = "Liam Neeson, Ralph Fiennes, Ben Kingsley",
                            Description = "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.",
                            Director = "Steven Spielberg",
                            Genre = "Biography",
                            Language = "English",
                            Origincountry = "USA",
                            PosterImage = "schindlerslist.jpg",
                            Title = "Schindler's List",
                            classification = "C",
                            duration = 195
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
