// <auto-generated />
using System;
using Galaxi.Movie.Persistence.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Galaxi.Movie.Persistence.Migrations
{
    [DbContext(typeof(MovieContextDb))]
    [Migration("20240804215026_updateRules")]
    partial class updateRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Galaxi.Movie.Data.Models.Film", b =>
                {
                    b.Property<Guid>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cast")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Director")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origincountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PosterImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("duration")
                        .HasColumnType("int");

                    b.HasKey("FilmId");

                    b.ToTable("Films", (string)null);

                    b.HasData(
                        new
                        {
                            FilmId = new Guid("f63a6702-af52-4f0a-8bce-aa84cf86b180"),
                            Cast = "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology.",
                            Director = "Christopher Nolan",
                            Genre = "Science Fiction",
                            Language = "English",
                            Origincountry = "USA",
                            PosterImage = "inception.jpg",
                            Title = "Inception",
                            classification = "B",
                            duration = 148
                        },
                        new
                        {
                            FilmId = new Guid("8d3885cd-9840-4b14-893b-89a280e92833"),
                            Cast = "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong",
                            Description = "A poor family schemes to become employed by a wealthy family.",
                            Director = "Bong Joon-ho",
                            Genre = "Thriller",
                            Language = "English",
                            Origincountry = "South Korea",
                            PosterImage = "parasite.jpg",
                            Title = "Parasite",
                            classification = "B15",
                            duration = 132
                        },
                        new
                        {
                            FilmId = new Guid("84af8500-2591-40b4-aa26-6247dcd574d1"),
                            Cast = "Marlon Brando, Al Pacino, James Caan",
                            Description = "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
                            Director = "Francis Ford Coppola",
                            Genre = "Crime",
                            Language = "English",
                            Origincountry = "USA",
                            PosterImage = "godfather.jpg",
                            Title = "The Godfather",
                            classification = "B15",
                            duration = 175
                        },
                        new
                        {
                            FilmId = new Guid("f97c04eb-38cd-4540-995a-e0f90a2ef5f2"),
                            Cast = "Audrey Tautou, Mathieu Kassovitz, Rufus",
                            Description = "Amélie is an innocent and naive girl in Paris with her own sense of justice.",
                            Director = "Jean-Pierre Jeunet",
                            Genre = "Romantic Comedy",
                            Language = "French",
                            Origincountry = "France",
                            PosterImage = "amelie.jpg",
                            Title = "Amélie",
                            classification = "AA",
                            duration = 122
                        },
                        new
                        {
                            FilmId = new Guid("a6276a11-dadf-46f7-b513-de1bff52d11d"),
                            Cast = "John Travolta, Uma Thurman, Samuel L. Jackson",
                            Description = "The lives of two mob hitmen, a boxer, and a pair of bandits intertwine in four tales of violence.",
                            Director = "Quentin Tarantino",
                            Genre = "Crime",
                            Language = "English",
                            Origincountry = "USA",
                            PosterImage = "pulpfiction.jpg",
                            Title = "Pulp Fiction",
                            classification = "C",
                            duration = 154
                        },
                        new
                        {
                            FilmId = new Guid("0680bd74-b6fb-4ca6-9878-f676c7d51936"),
                            Cast = "Anthony Gonzalez, Gael García Bernal, Benjamin Bratt",
                            Description = "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead.",
                            Director = "Lee Unkrich",
                            Genre = "Animation",
                            Language = "English",
                            Origincountry = "USA",
                            PosterImage = "coco.jpg",
                            Title = "Coco",
                            classification = "AA",
                            duration = 105
                        },
                        new
                        {
                            FilmId = new Guid("182cdb5d-9ed2-400b-922c-f9e0521dde3e"),
                            Cast = "Christian Bale, Heath Ledger, Aaron Eckhart",
                            Description = "Batman begins his fight against crime in Gotham.",
                            Director = "Christopher Nolan",
                            Genre = "Action",
                            Language = "English",
                            Origincountry = "USA",
                            PosterImage = "darkknight.jpg",
                            Title = "The Dark Knight",
                            classification = "B",
                            duration = 152
                        },
                        new
                        {
                            FilmId = new Guid("b77dacc2-d72d-4258-a8ad-01e97f4ad219"),
                            Cast = "Rumi Hiiragi, Miyu Irino, Mari Natsuki",
                            Description = "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.",
                            Director = "Hayao Miyazaki",
                            Genre = "Animation",
                            Language = "English",
                            Origincountry = "Japan",
                            PosterImage = "spiritedaway.jpg",
                            Title = "Spirited Away",
                            classification = "A",
                            duration = 125
                        },
                        new
                        {
                            FilmId = new Guid("8291ffb2-6747-470a-865f-dac56801e01c"),
                            Cast = "Ivana Baquero, Ariadna Gil, Sergi López",
                            Description = "In the falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.",
                            Director = "Guillermo del Toro",
                            Genre = "Fantasy",
                            Language = "Spanish",
                            Origincountry = "Spain",
                            PosterImage = "panslabyrinth.jpg",
                            Title = "Pan's Labyrinth",
                            classification = "B15",
                            duration = 118
                        },
                        new
                        {
                            FilmId = new Guid("3b8f4f14-b7cb-4d54-805a-ed7358c0858f"),
                            Cast = "Liam Neeson, Ralph Fiennes, Ben Kingsley",
                            Description = "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.",
                            Director = "Steven Spielberg",
                            Genre = "Biography",
                            Language = "English",
                            Origincountry = "USA",
                            PosterImage = "schindlerslist.jpg",
                            Title = "Schindler's List",
                            classification = "C",
                            duration = 195
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
